// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
public class Web {
        private WebDriver driver;
        private Map<String, Object> vars;
        JavascriptExecutor js;
        @Before
        public void setUp() {
                driver = new FirefoxDriver();
                js = (JavascriptExecutor) driver;
                vars = new HashMap<String, Object>();
        }
        @After
        public void tearDown() {
                driver.quit();
        }
        @Test
        public void web() {
                driver.get("https://accounts.google.com/ServiceLogin/signinchooser?service=mail&passive=true&rm=false&continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&ss=1&scc=1&ltmpl=default&ltmplcache=2&emr=1&osid=1&flowName=GlifWebSignIn&flowEntry=ServiceLogin");
                driver.manage().window().setSize(new Dimension(611, 796));
                driver.findElement(By.cssSelector(".JDAKTe:nth-child(3) .BHzsHc")).click();
                driver.findElement(By.id("identifierId")).click();
                driver.findElement(By.id("identifierId")).sendKeys("2014webdriver@gmail.com");
                driver.findElement(By.cssSelector(".RveJvd")).click();
                driver.findElement(By.xpath("//input[@name=\'password\']")).sendKeys("webdriver2014");
                driver.findElement(By.cssSelector("#passwordNext .RveJvd")).click();
                {
                        WebElement element = driver.findElement(By.cssSelector(".gb_Ra"));
                        Actions builder = new Actions(driver);
                        builder.moveToElement(element).perform();
                }
                {
                        WebElement element = driver.findElement(By.tagName("body"));
                        Actions builder = new Actions(driver);
                        builder.moveToElement(element, 0, 0).perform();
                }
                {
                        WebElement element = driver.findElement(By.cssSelector(".gb_Ia"));
                        Actions builder = new Actions(driver);
                        builder.moveToElement(element).perform();
                }
                driver.findElement(By.cssSelector(".gb_Ia")).click();
                {
                        WebElement element = driver.findElement(By.tagName("body"));
                        Actions builder = new Actions(driver);
                        builder.moveToElement(element, 0, 0).perform();
                }
                {
                        WebElement element = driver.findElement(By.id("gb_71"));
                        Actions builder = new Actions(driver);
                        builder.moveToElement(element).perform();
                }
                driver.findElement(By.id("gb_71")).click();
                assertThat(driver.getTitle(), is("*Inbox*"));
                try {
                        Thread.sleep(4000);
                } catch (InterruptedException e) {
                        e.printStackTrace();
                }
        }
}
